'use client';
import React from 'react';
import LayoutProductList from '@/components/layouts/layout_products_list/page';
import ProductItem from '@/components/arraysData/productItems/page';

import LayoutContent from '@/components/layouts/layout_content_home/page';

import LayoutProductPage from '@/components/layouts/layout_cover_products_page/page';
import st from '@/app/products/huongboket/huongboket.module.css';

const AllProducts: React.FC = () => {
  return (
    <>
      <LayoutContent>
        <LayoutProductPage>
          <div className={st.overTitleProduct}>
            <p className={st.titleProduct}>TẤT CẢ SẢN PHẨM</p>
          </div>
          <LayoutProductList>
            {/* Tu Hú */}
            <ProductItem
              imgSrc="/products/tuhuthuong/NuTuHu1.jpg"
              imgSrc1="/products/tuhuthuong/NuTuHu2.jpg"
              imgSrc2="/products/tuhuthuong/NuTuHu3.jpg"
              imgSrc3="/products/tuhuthuong/NuTuHu4.jpg"
              imgSrc4="/products/tuhuthuong/NuTuHu3.jpg"
              title="Hương Nụ"
              price="2.000 - 3.000 VNĐ / nụ"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như rễ găng núi, rễ hương lâu, keo bời lời, cùng một số thảo dược khác. "
              muithom="hương tu hú thường có mùi hương đậm, nguyên thủy và mạnh mẽ. hương tu hú thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương mạnh mẽ và lâu dài. Tạo cho con người cảm giác dễ chịu, sảng khoái nhất. "
              kichthuoc="Nụ cao 4.3 cm, cháy trong 20p"
              theloai="Nhang nụ, có lỗ nhỏ dưới đáy nụ để cắm chu tăm. Thích hợp để trên những chân thắp nụ, tỏa khói đẹp."
              priceSi="LIÊN HỆ"
              priceLe="2.000 - 3.000 VNĐ / nụ"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/tuhuthuong/TamDoTH40_11.jpg"
              imgSrc1="/products/tuhuthuong/TamDoTH40_22.jpg"
              imgSrc2="/products/tuhuthuong/TamDoTH40_33.jpg"
              imgSrc3="/products/tuhuthuong/TamDoTH40_44.jpg"
              imgSrc4="/products/tuhuthuong/TamDoTH40_55.jpg"
              title="Hương Cây | Tăm Đỏ"
              price="80.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như rễ găng núi, rễ hương lâu, keo bời lời, cùng một số thảo dược khác. "
              muithom="hương tu hú thường có mùi hương đậm, nguyên thủy và mạnh mẽ. hương tu hú thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương mạnh mẽ và lâu dài. Tạo cho con người cảm giác dễ chịu, sảng khoái nhất. "
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm đỏ theo truyền thống, phù hợp cho thờ cúng, tôn nghiêm."
              priceSi="LIÊN HỆ"
              priceLe="80.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/tuhuthuong/TamTrangBQ40_1.jpg"
              imgSrc1="/products/tuhuthuong/TamTrangBQ40_2.jpg"
              imgSrc2="/products/tuhuthuong/TamTrangBQ40_3.jpg"
              imgSrc3="/products/tuhuthuong/TamTrangBQ40_1.jpg"
              imgSrc4="/products/tuhuthuong/TamTrangBQ40_2.jpg"
              title="Hương Cây | Tăm Trắng"
              price="80.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như rễ găng núi, rễ hương lâu, keo bời lời, cùng một số thảo dược khác.  "
              muithom="hương tu hú thường có mùi hương đậm, nguyên thủy và mạnh mẽ. hương tu hú thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương mạnh mẽ và lâu dài. Tạo cho con người cảm giác dễ chịu, sảng khoái nhất."
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm trắng phù hợp với những bạn theo đuổi sự nhẹ nhàng từ tự nhiên, tìm về sự thư giản, cảm giác thoải mái. "
              priceSi="LIÊN HỆ"
              priceLe="80.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/tuhuthuong/CayToBQ80_1.jpg"
              imgSrc1="/products/tuhuthuong/CayToBQ80_2.jpg"
              imgSrc2="/products/tuhuthuong/CayToBQ80_3.jpg"
              imgSrc3="/products/tuhuthuong/CayToBQ80_1.jpg"
              imgSrc4="/products/tuhuthuong/CayToBQ80_2.jpg"
              title="Hương Cây To | 80cm"
              price="4.000 VNĐ/cây"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như rễ găng núi, rễ hương lâu, keo bời lời, cùng một số thảo dược khác. "
              muithom="hương tu hú thường có mùi hương đậm, nguyên thủy và mạnh mẽ. hương tu hú thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương mạnh mẽ và lâu dài. Tạo cho con người cảm giác dễ chịu, sảng khoái nhất."
              kichthuoc="Có 80 cm, thời gian cháy gần 4 giờ. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây to với kích thước 80cm, phù hợp để thắp các dịp lễ lớn, các đám ở tộc, hay đám cần thời canh nhang lâu."
              priceSi="LIÊN HỆ"
              priceLe="4.000 VNĐ/cây"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            {/* Bài Quảng Hương */}
            <ProductItem
              imgSrc="/products/baiquang/NuBaiQuang1.jpg"
              imgSrc1="/products/baiquang/NuBaiQuang2.jpg"
              imgSrc2="/products/baiquang/NuBaiQuang3.jpg"
              imgSrc3="/products/baiquang/NuBaiQuang4.jpg"
              imgSrc4="/products/baiquang/NuBaiQuang5.jpg"
              title="Hương Nụ"
              price="2.000 - 3.000 VNĐ / nụ"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như rễ găng núi, rễ hương bài, rễ quýt rừng, keo bời lời, cùng một số thảo dược khác. "
              muithom="hương bài quảng thường có mùi hương đậm, nguyên thủy và mạnh mẽ. Hương bài quảng thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương mạnh mẽ và lâu dài. Hương bài quảng thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương đậm đà, ngạt ngào lan tỏa. "
              kichthuoc="Nụ cao 4.3 cm, cháy trong 20p"
              theloai="Nhang nụ, có lỗ nhỏ dưới đáy nụ để cắm chu tăm. Thích hợp để trên những chân thắp nụ, tỏa khói đẹp."
              priceSi="LIÊN HỆ"
              priceLe="2.000 - 3.000 VNĐ / nụ"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/baiquang/TamDoBQ40_1.jpg"
              imgSrc1="/products/baiquang/TamDoBQ40_2.jpg"
              imgSrc2="/products/baiquang/TamDoBQ40_3.jpg"
              imgSrc3="/products/baiquang/TamDoBQ40_4.jpg"
              imgSrc4="/products/baiquang/TamDoBQ40_5.jpg"
              title="Hương Cây | Tăm Đỏ"
              price="120.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như rễ găng núi, rễ hương bài, rễ quýt rừng, keo bời lời, cùng một số thảo dược khác. "
              muithom="hương bài quảng thường có mùi hương đậm, nguyên thủy và mạnh mẽ. Hương bài quảng thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương mạnh mẽ và lâu dài. Hương bài quảng thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương đậm đà, ngạt ngào lan tỏa. "
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm đỏ theo truyền thống, phù hợp cho thờ cúng, tôn nghiêm."
              priceSi="LIÊN HỆ"
              priceLe="120.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/baiquang/TamTrangBQ40_1.jpg"
              imgSrc1="/products/baiquang/TamTrangBQ40_2.jpg"
              imgSrc2="/products/baiquang/TamTrangBQ40_3.jpg"
              imgSrc3="/products/baiquang/TamTrangBQ40_1.jpg"
              imgSrc4="/products/baiquang/TamTrangBQ40_2.jpg"
              title="Hương Cây | Tăm Trắng"
              price="120.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như rễ găng núi, rễ hương bài, rễ quýt rừng, keo bời lời, cùng một số thảo dược khác. "
              muithom="hương bài quảng thường có mùi hương đậm, nguyên thủy và mạnh mẽ. Hương bài quảng thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương mạnh mẽ và lâu dài. Hương bài quảng thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương đậm đà, ngạt ngào lan tỏa."
              kichthuoc="Có loại 30,35,40,50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm trắng phù hợp với những bạn theo đuổi sự nhẹ nhàng từ tự nhiên, tìm về sự thư giản, cảm giác thoải mái. "
              priceSi="LIÊN HỆ"
              priceLe="120.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/baiquang/CayToBQ80_1.jpg"
              imgSrc1="/products/baiquang/CayToBQ80_2.jpg"
              imgSrc2="/products/baiquang/CayToBQ80_3.jpg"
              imgSrc3="/products/baiquang/CayToBQ80_1.jpg"
              imgSrc4="/products/baiquang/CayToBQ80_2.jpg"
              title="Hương Cây To | 80cm"
              price="4.000 VNĐ/cây"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như rễ găng núi, rễ hương bài, rễ quýt rừng, keo bời lời, cùng một số thảo dược khác. "
              muithom="hương bài quảng thường có mùi hương đậm, nguyên thủy và mạnh mẽ. Hương bài quảng thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương mạnh mẽ và lâu dài. Hương bài quảng thường được ưa chuộng vì tính tinh khiết và khả năng tạo ra mùi hương đậm đà, ngạt ngào lan tỏa."
              kichthuoc="Có 80 cm, thời gian cháy gần 4 giờ. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây to với kích thước 80cm, phù hợp để thắp các dịp lễ lớn, các đám ở tộc, hay đám cần thời canh nhang lâu."
              priceSi="LIÊN HỆ"
              priceLe="4.000 VNĐ/cây"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            {/* TRẦM */}
            <ProductItem
              imgSrc="/products/tram/NuTram1.jpg"
              imgSrc1="/products/tram/NuTram2.jpg"
              imgSrc2="/products/tram/NuTram3.jpg"
              imgSrc3="/products/tram/NuTram4.jpg"
              imgSrc4="/products/tram/NuTram5.jpg"
              title="Hương Nụ"
              price="3.500 - 4.000 VNĐ / nụ"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột trầm và keo bời lời."
              muithom="Hương Trầm có mùi thơm ấm áp và đậm đà. Khi đốt trầm hương, mùi hương trầm như thể len lõi vào từng tế bào thần kinh giúp cho tâm ta tĩnh, trí ta an. "
              kichthuoc="Nụ cao 4.3 cm, cháy trong 20p"
              theloai="Nhang nụ, có lỗ nhỏ dưới đáy nụ để cắm chu tăm. Thích hợp để trên những chân thắp nụ, tỏa khói đẹp."
              priceSi="LIÊN HỆ"
              priceLe="3.500 - 4.000 VNĐ / nụ"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/tram/TamDoT40_1.jpg"
              imgSrc1="/products/tram/TamDoT40_2.jpg"
              imgSrc2="/products/tram/TamDoT40_3.jpg"
              imgSrc3="/products/tram/TamDoT40_4.jpg"
              imgSrc4="/products/tram/TamDoT40_5.jpg"
              title="Hương Cây | Tăm Đỏ"
              price="480.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột trầm và keo bời lời."
              muithom="Hương Trầm có mùi thơm ấm áp và đậm đà. Khi đốt trầm hương, mùi hương trầm như thể len lõi vào từng tế bào thần kinh giúp cho tâm ta tĩnh, trí ta an. "
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm đỏ theo truyền thống, phù hợp cho thờ cúng, tôn nghiêm."
              priceSi="LIÊN HỆ"
              priceLe="480.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            <ProductItem
              imgSrc="/products/tram/TamTrangT35_1.jpg"
              imgSrc1="/products/tram/TamTrangT35_2.jpg"
              imgSrc2="/products/tram/TamTrangT35_3.jpg"
              imgSrc3="/products/tram/TamTrangT35_4.jpg"
              imgSrc4="/products/tram/TamTrangT35_5.jpg"
              title="Hương Cây | Tăm Trắng"
              price="480.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột trầm và keo bời lời. "
              muithom="Hương Trầm có mùi thơm ấm áp và đậm đà. Khi đốt trầm hương, mùi hương trầm như thể len lõi vào từng tế bào thần kinh giúp cho tâm ta tĩnh, trí ta an. "
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm trắng phù hợp với những bạn theo đuổi sự nhẹ nhàng từ tự nhiên, tìm về sự thư giản, cảm giác thoải mái."
              priceSi="LIÊN HỆ"
              priceLe="480.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/tram/CayToT80_1.jpg"
              imgSrc1="/products/tram/CayToT80_2.jpg"
              imgSrc2="/products/tram/CayToT80_3.jpg"
              imgSrc3="/products/tram/CayToT80_4.jpg"
              imgSrc4="/products/tram/CayToT80_5.jpg"
              title="Hương Cây To | 80cm"
              price="7.000 VNĐ/cây"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột trầm và keo bời lời. "
              muithom="Hương Trầm có mùi thơm ấm áp và đậm đà. Khi đốt trầm hương, mùi hương trầm như thể len lõi vào từng tế bào thần kinh giúp cho tâm ta tĩnh, trí ta an. "
              kichthuoc="Có 80 cm, thời gian cháy gần 4 giờ. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây to với kích thước 80cm, phù hợp để thắp các dịp lễ lớn, các đám ở tộc, hay đám tiệc cần thời gian nhang lâu."
              priceSi="LIÊN HỆ"
              priceLe="7.000 VNĐ/cây"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            {/* BO KET */}
            <ProductItem
              imgSrc="/products/boket/NuBoKet1.jpg"
              imgSrc1="/products/boket/NuBoKet2.jpg"
              imgSrc2="/products/boket/NuBoKet3.jpg"
              imgSrc3="/products/boket/NuBoKet4.jpg"
              imgSrc4="/products/boket/NuBoKet5.jpg"
              title="Nhang Nụ"
              price="2.000 - 3.000 VNĐ / nụ"
              huonglieu=" là sự kết hợp của các nguyên liệu từ tự nhiên như trái bồ kết, vỏ bưởi, rễ hương nhu, cây tía tô, keo bời lời và một số thảo dược khác."
              muithom="nụ nhang bồ kết với mùi thơm đặc trưng và hơi hăng của bồ kết giúp mũi được thông, dễ thở, chống suy giảm hô hấp. Khói cay của bồ kết còn khiến kiến, gián, ruồi muỗi sợ hãi."
              kichthuoc="Nụ cao 4.3 cm, cháy trong 20p"
              theloai="Nhang nụ, có lỗ nhỏ dưới đáy nụ để cắm chu tăm. Thích hợp để trên những chân thắp nụ, tỏa khói đẹp."
              priceSi="LIÊN HỆ"
              priceLe="2.000 - 3.000 VNĐ / nụ"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/boket/TamDoBK40_1.jpg"
              imgSrc1="/products/boket/TamDoBK40_2.jpg"
              imgSrc2="/products/boket/TamDoBK40_3.jpg"
              imgSrc3="/products/boket/TamDoBK40_4.jpg"
              imgSrc4="/products/boket/TamDoBK40_5.jpg"
              title="Nhang Cây | Tăm Đỏ"
              price="130.000 VNĐ / 500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như trái bồ kết, vỏ bưởi, rễ hương nhu, cây tía tô, keo bời lời và một số thảo dược khác."
              muithom="nhang cây bồ kết với mùi thơm đặc trưng và hơi hăng của bồ kết giúp mũi được thông, dễ thở, chống suy giảm hô hấp. Khói cay của bồ kết còn khiến kiến, gián, ruồi muỗi sợ hãi. Và theo dân gian hương bồ kết có thể hóa giải tà khí."
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm đỏ theo truyền thống, phù hợp cho thờ cúng, tôn nghiêm."
              priceSi="LIÊN HỆ"
              priceLe="130.000 VNĐ / 500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            <ProductItem
              imgSrc="/products/boket/TamTrangBK35_1.jpg"
              imgSrc1="/products/boket/TamTrangBK35_2.jpg"
              imgSrc2="/products/boket/TamTrangBK35_3.jpg"
              imgSrc3="/products/boket/TamTrangBK35_1.jpg"
              imgSrc4="/products/boket/TamTrangBK35_2.jpg"
              title="Nhang Cây | Tăm Trắng"
              price="130.000 VNĐ / 500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như trái bồ kết, vỏ bưởi, rễ hương nhu, cây tía tô, keo bời lời và một số thảo dược khác. "
              muithom="nhang cây bồ kết với mùi thơm đặc trưng và hơi hăng của bồ kết giúp mũi được thông, dễ thở, chống suy giảm hô hấp. Khói cay của bồ kết còn khiến kiến, gián, ruồi muỗi sợ hãi. Và theo dân gian hương bồ kết có thể hóa giải tà khí."
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm trắng phù hợp với những bạn theo đuổi sự nhẹ nhàng từ tự nhiên, tìm về sự thư giản, cảm giác thoải mái. "
              priceSi="LIÊN HỆ"
              priceLe="130.000 VNĐ / 500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/boket/CayToBK80_1.jpg"
              imgSrc1="/products/boket/CayToBK80_2.jpg"
              imgSrc2="/products/boket/CayToBK80_1.jpg"
              imgSrc3="/products/boket/CayToBK80_2.jpg"
              imgSrc4="/products/boket/CayToBK80_1.jpg"
              title="Nhang Cây To"
              price="4.000 VNĐ / cây"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như trái bồ kết, vỏ bưởi, rễ hương nhu, cây tía tô, keo bời lời và một số thảo dược khác. "
              muithom="nhang cây to bồ kết với mùi thơm đặc trưng và hơi hăng của bồ kết giúp mũi được thông, dễ thở, chống suy giảm hô hấp. Khói cay của bồ kết còn khiến kiến, gián, ruồi muỗi sợ hãi. Và theo dân gian hương bồ kết có thể hóa giải tà khí."
              kichthuoc="Có 80 cm, thời gian cháy gần 4 giờ. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp. "
              theloai="Nhang cây to với kích thước 80cm, phù hợp để thắp các dịp lễ lớn, các đám ở tộc, hay đám cần thời gian nhang lâu."
              priceSi="4.000 VNĐ / cây"
              priceLe="LIÊN HỆ"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            {/* Cà phê */}
            <ProductItem
              imgSrc="/products/caphe/NuCaPhe1.jpg"
              imgSrc1="/products/caphe/NuCaPhe2.jpg"
              imgSrc2="/products/caphe/NuCaPhe3.jpg"
              imgSrc3="/products/caphe/NuCaPhe4.jpg"
              imgSrc4="/products/caphe/NuCaPhe5.jpg"
              title="2.000 - 3.000 VNĐ / nụ"
              price="LIÊN HỆ"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột cà phê, rễ hương lau, keo bời lời và cùng một số thảo dược khác."
              muithom="mùi thơm của hương cà phê này sẽ tùy thuộc vào mỗi loại cà phê khác nhau. Một số loại có mùi ngọt, một số loại có mùi cháy của than và giống cà phê đặc biệt có mùi thơm của hoa quả, trái cây họ cam quýt. Mùi cà phê này sẽ giúp bạn cảm thấy sảng khoái và tỉnh táo."
              kichthuoc="Nụ cao 4.3 cm, cháy trong 20p"
              theloai="Nhang nụ, có lỗ nhỏ dưới đáy nụ để cắm chu tăm. Thích hợp để trên những chân thắp nụ, tỏa khói đẹp."
              priceSi="LIÊN HỆ"
              priceLe="2.000 - 3.000 VNĐ / nụ"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/caphe/TamDoCP40_1.jpg"
              imgSrc1="/products/caphe/TamDoCP40_2.jpg"
              imgSrc2="/products/caphe/TamDoCP40_3.jpg"
              imgSrc3="/products/caphe/TamDoCP40_4.jpg"
              imgSrc4="/products/caphe/TamDoCP40_5.jpg"
              title="Hương Cây | Tăm Đỏ"
              price="112.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột cà phê, rễ hương lau, keo bời lời và cùng một số thảo dược khác."
              muithom="mùi thơm của hương cà phê này sẽ tùy thuộc vào mỗi giống, hay loại cà phê khác nhau. Một số loại có mùi ngọt, một số loại có mùi cháy của than và giống cà phê đặc biệt có mùi thơm của hoa quả, trái cây họ cam quýt. Mùi cà phê này sẽ giúp bạn cảm thấy sảng khoái và tỉnh táo."
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm đỏ theo truyền thống, phù hợp cho thờ cúng, tôn nghiêm."
              priceSi="LIÊN HỆ"
              priceLe="112.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            <ProductItem
              imgSrc="/products/caphe/TamTrangCP40_3.jpg"
              imgSrc1="/products/caphe/TamTrangCP40_1.jpg"
              imgSrc2="/products/caphe/TamTrangCP40_2.jpg"
              imgSrc3="/products/caphe/TamTrangCP40_3.jpg"
              imgSrc4="/products/caphe/TamTrangCP40_1.jpg"
              title="Hương Cây | Tăm Trắng"
              price="112.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột cà phê, rễ hương lau, keo bời lời và cùng một số thảo dược khác. "
              muithom="mùi thơm của hương cà phê này sẽ tùy thuộc vào mỗi giống, hay loại cà phê khác nhau. Một số loại có mùi ngọt, một số loại có mùi cháy của than và giống cà phê đặc biệt có mùi thơm của hoa quả, trái cây họ cam quýt. Mùi cà phê này sẽ giúp bạn cảm thấy sảng khoái và tỉnh táo."
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm trắng phù hợp với những bạn theo đuổi sự nhẹ nhàng từ tự nhiên, tìm về sự thư giản, cảm giác thoải mái. "
              priceSi="LIÊN HỆ"
              priceLe="112.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/caphe/CayToCP80_1.jpg"
              imgSrc1="/roducts/caphe/CayToCP80_1.jpg"
              imgSrc2="/roducts/caphe/CayToCP80_2.jpg"
              imgSrc3="/roducts/caphe/CayToCP80_1.jpg"
              imgSrc4="/roducts/caphe/CayToCP80_2.jpg"
              title="Hương Cây To | 80cm"
              price="4.000 VNĐ/cây"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột cà phê, rễ hương lau, keo bời lời và cùng một số thảo dược khác. "
              muithom="mùi thơm của hương cà phê này sẽ tùy thuộc vào mỗi giống, hay loại cà phê khác nhau. Một số loại có mùi ngọt, một số loại có mùi cháy của than và giống cà phê đặc biệt có mùi thơm của hoa quả, trái cây họ cam quýt. Mùi cà phê này sẽ giúp bạn cảm thấy sảng khoái và tỉnh táo."
              kichthuoc="Có 80 cm, thời gian cháy gần 4 giờ. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai=" Nhang cây to với kích thước 80cm, phù hợp để thắp các dịp lễ lớn, các đám ở tộc, hay đám cần thời canh nhang lâu."
              priceSi="LIÊN HỆ"
              priceLe="4.000 VNĐ/cây"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            {/* Ngải Cứu */}
            <ProductItem
              imgSrc="/products/ngaicuu/NuNgaiCuu1.jpg"
              imgSrc1="/products/ngaicuu/NuNgaiCuu2.jpg"
              imgSrc2="/products/ngaicuu/NuNgaiCuu3.jpg"
              imgSrc3="/products/ngaicuu/NuNgaiCuu4.jpg"
              imgSrc4="/products/ngaicuu/NuNgaiCuu5.jpg"
              title="Hương Nụ"
              price="2.000 - 3.000/nụ"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như cây ngãi cứu, bột quế, keo bời lời và cùng một số thảo dược khác. "
              muithom="mùi thơm của hương ngãi cứu có mùi hương thảo dược, thanh khiết và mát mẻ. Giúp thư giản tinh thần, an thần và định tâm. Làm sạch không gian và tạo cảm giác dễ chịu."
              kichthuoc="Nụ cao 4.3 cm, cháy trong 25-30p"
              theloai=" Nhang nụ, có lỗ nhỏ dưới đáy nụ để cắm chu tăm. Thích hợp để trên những chân thắp nụ, tỏa khói đẹp."
              priceSi="LIÊN HỆ"
              priceLe="2.000 - 3.000/nụ"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/ngaicuu/TamDoNC40_1.jpg"
              imgSrc1="/products/ngaicuu/TamDoNC40_2.jpg"
              imgSrc2="/products/ngaicuu/TamDoNC40_3.jpg"
              imgSrc3="/products/ngaicuu/TamDoNC40_4.jpg"
              imgSrc4="/products/ngaicuu/TamDoNC40_5.jpg"
              title="Hương Cây | Tăm Đỏ"
              price="130.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như cây ngãi cứu, bột quế, keo bời lời và cùng một số thảo dược khác."
              muithom="mùi thơm của hương ngãi cứu có mùi hương thảo dược, thanh khiết và mát mẻ. Giúp thư giản tinh thần, an thần và định tâm. Làm sạch không gian và tạo cảm giác dễ chịu."
              kichthuoc="Có loại 35,40, 60 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm đỏ theo truyền thống, phù hợp cho thờ cúng, tôn nghiêm."
              priceSi="LIÊN HỆ"
              priceLe="130.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            <ProductItem
              imgSrc="/products/ngaicuu/TamTrangNC35_1.jpg"
              imgSrc1="/products/ngaicuu/TamTrangNC35_3.jpg"
              imgSrc2="/products/ngaicuu/TamTrangNC35_2.jpg"
              imgSrc3="/products/ngaicuu/TamTrangNC35_1.jpg"
              imgSrc4="/products/ngaicuu/TamTrangNC35_2.jpg"
              title="Hương Cây | Tăm Trắng"
              price="130.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như cây ngãi cứu, bột quế, keo bời lời và cùng một số thảo dược khác. "
              muithom="mùi thơm của hương ngãi cứu có mùi hương thảo dược, thanh khiết và mát mẻ. Giúp thư giản tinh thần, an thần và định tâm. Làm sạch không gian và tạo cảm giác dễ chịu."
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm trắng phù hợp với những bạn theo đuổi sự nhẹ nhàng từ tự nhiên, tìm về sự thư giản, cảm giác thoải mái. "
              priceSi="LIÊN HỆ"
              priceLe="130.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/ngaicuu/CayToNC80_1.jpg"
              imgSrc1="/products/ngaicuu/CayToNC80_1.jpg"
              imgSrc2="/products/ngaicuu/CayToNC80_2.jpg"
              imgSrc3="/products/ngaicuu/CayToNC80_1.jpg"
              imgSrc4="/products/ngaicuu/CayToNC80_2.jpg"
              title="Hương Cây To | 80cm"
              price="4.000 VNĐ/cây"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như cây ngãi cứu, bột quế, keo bời lời và cùng một số thảo dược khác."
              muithom="mùi thơm của hương ngãi cứu có mùi hương thảo dược, thanh khiết và mát mẻ. Giúp thư giản tinh thần, an thần và định tâm. Làm sạch không gian và tạo cảm giác dễ chịu."
              kichthuoc="Có 80 cm, thời gian cháy gần 4 giờ. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây to với kích thước 80cm, phù hợp để thắp các dịp lễ lớn, các đám ở tộc, hay đám cần thời canh nhang lâu."
              priceSi="LIÊN HỆ"
              priceLe="4.000 VNĐ/cây"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            {/* Quế */}
            <ProductItem
              imgSrc="/products/que/NuQue1.jpg"
              imgSrc1="/products/que/NuQue2.jpg"
              imgSrc2="/products/que/NuQue3.jpg"
              imgSrc3="/products/que/NuQue4.jpg"
              imgSrc4="/products/que/NuQue5.jpg"
              title="Hương Nụ"
              price="2.000 - 3.000 VNĐ/nụ"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột quế, hoa hồi, keo bời lời và cùng một số thảo dược khác."
              muithom="hương quế có mùi thơm ấm áp và ngọt ngào. Nhang quế có mùi thơm nồng dễ chịu, kích thích trí não, giúp thư giãn,… và một số công dụng cho sức khỏe. Khói nhang quế có tác dụng xua đuổi các loại côn trùng bay vào nhà, như muỗi, ong. An toàn cho sức khỏe con người. "
              kichthuoc="Nụ cao 4.3 cm, cháy trong 20p"
              theloai="Nhang nụ, có lỗ nhỏ dưới đáy nụ để cắm chu tăm. Thích hợp để trên những chân thắp nụ, tỏa khói đẹp."
              priceSi="LIÊN HỆ"
              priceLe="2.000 - 3.000 VNĐ/nụ"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/que/TamDoQ40_1.jpg"
              imgSrc1="/products/que/TamDoQ40_2.jpg"
              imgSrc2="/products/que/TamDoQ40_3.jpg"
              imgSrc3="/products/que/TamDoQ40_4.jpg"
              imgSrc4="/products/que/TamDoQ40_5.jpg"
              title="Hương Cây | Tăm Đỏ"
              price="60.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột quế, hoa hồi, keo bời lời và cùng một số thảo dược khác. "
              muithom="hương quế có mùi thơm ấm áp và ngọt ngào. Nhang quế có mùi thơm nồng dễ chịu, kích thích trí não, giúp thư giãn,… và một số công dụng cho sức khỏe. Khói nhang quế có tác dụng xua đuổi các loại côn trùng bay vào nhà, như muỗi, ong. An toàn cho sức khỏe con người. "
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm đỏ theo truyền thống, phù hợp cho thờ cúng, tôn nghiêm."
              priceSi="LIÊN HỆ"
              priceLe="60.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            <ProductItem
              imgSrc="/products/que/TamTrangQ40_1.jpg"
              imgSrc1="/products/que/TamTrangQ40_2.jpg"
              imgSrc2="/products/que/TamTrangQ40_3.jpg"
              imgSrc3="/products/que/TamTrangQ40_1.jpg"
              imgSrc4="/products/que/TamTrangQ40_2.jpg"
              title="Hương Cây | Tăm Trắng"
              price="60.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột quế, hoa hồi, keo bời lời và cùng một số thảo dược khác."
              muithom="hương quế có mùi thơm ấm áp và ngọt ngào. Nhang quế có mùi thơm nồng dễ chịu, kích thích trí não, giúp thư giãn,… và một số công dụng cho sức khỏe. Khói nhang quế có tác dụng xua đuổi các loại côn trùng bay vào nhà, như muỗi, ong. An toàn cho sức khỏe con người. "
              kichthuoc="NCó loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm trắng phù hợp với những bạn theo đuổi sự nhẹ nhàng từ tự nhiên, tìm về sự thư giản, cảm giác thoải mái. "
              priceSi="LIÊN HỆ"
              priceLe="60.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/que/CayToQue80_1.jpg"
              imgSrc1="/products/que/CayToQue80_1.jpg"
              imgSrc2="/products/que/CayToQue80_2.jpg"
              imgSrc3="/products/que/CayToQue80_1.jpg"
              imgSrc4="/products/que/CayToQue80_2.jpg"
              title="Hương Cây To | 80cm"
              price="4.000 VNĐ/cây"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như bột quế, hoa hồi, keo bời lời và cùng một số thảo dược khác."
              muithom="hương quế có mùi thơm ấm áp và ngọt ngào. Nhang quế có mùi thơm nồng dễ chịu, kích thích trí não, giúp thư giãn,… và một số công dụng cho sức khỏe. Khói nhang quế có tác dụng xua đuổi các loại côn trùng bay vào nhà, như muỗi, ong. An toàn cho sức khỏe con người. "
              kichthuoc="Có 80 cm, thời gian cháy gần 4 giờ. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây to với kích thước 80cm, phù hợp để thắp các dịp lễ lớn, các đám ở tộc, hay đám cần thời canh nhang lâu."
              priceSi="LIÊN HỆ"
              priceLe="4.000 VNĐ/cây"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            {/* Sả */}
            <ProductItem
              imgSrc="/products/sa/NuSa1.jpg"
              imgSrc1="/products/sa/NuSa2.jpg"
              imgSrc2="/products/sa/NuSa3.jpg"
              imgSrc3="/products/sa/NuSa4.jpg"
              imgSrc4="/products/sa/NuSa5.jpg"
              title="Hương Nụ"
              price="2.000 - 3.000 VNĐ/ nụ"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như cây sả, keo bời lời cùng một số thảo dược khác."
              muithom="hương sả có mùi thơm tươi mát, mạnh mẽ và kích thích. Tạo sự tỉnh táo và tăng sự tập trung.Xua đuổi muỗi mà không ảnh hướng đến sức khỏe còn người."
              kichthuoc="Nụ cao 4.3 cm, cháy trong 20p"
              theloai="Nhang nụ, có lỗ nhỏ dưới đáy nụ để cắm chu tăm. Thích hợp để trên những chân thắp nụ, tỏa khói đẹp."
              priceSi="LIÊN HỆ"
              priceLe="2.000 - 3.000 VNĐ / nụ"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/sa/TamDoSa40_1.jpg"
              imgSrc1="/products/sa/TamDoSa40_2.jpg"
              imgSrc2="/products/sa/TamDoSa40_3.jpg"
              imgSrc3="/products/sa/TamDoSa40_4.jpg"
              imgSrc4="/products/sa/TamDoSa40_5.jpg"
              title="Hương Cây | Tăm Đỏ"
              price="80.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như cây sả, keo bời lời cùng một số thảo dược khác."
              muithom=" hương sả có mùi thơm tươi mát, mạnh mẽ và kích thích. Tạo sự tỉnh táo và tăng sự tập trung.Xua đuổi muỗi mà không ảnh hướng đến sức khỏe còn người."
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm đỏ theo truyền thống, phù hợp cho thờ cúng, tôn nghiêm."
              priceSi="LIÊN HỆ"
              priceLe="80.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />

            <ProductItem
              imgSrc="/products/sa/TamTrangSa35_1.jpg"
              imgSrc1="/products/sa/TamTrangSa35_2.jpg"
              imgSrc2="/products/sa/TamTrangSa35_3.jpg"
              imgSrc3="/products/sa/TamTrangSa35_1.jpg"
              imgSrc4="/products/sa/TamTrangSa35_3.jpg"
              title="Hương Cây | Tăm Trắng"
              price="80.000 VNĐ/500g"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như cây sả, keo bời lời cùng một số thảo dược khác. "
              muithom="hương sả có mùi thơm tươi mát, mạnh mẽ và kích thích. Tạo sự tỉnh táo và tăng sự tập trung.Xua đuổi muỗi mà không ảnh hướng đến sức khỏe còn người."
              kichthuoc="Có loại 30, 35, 40, 50 cm. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây với chu tăm trắng phù hợp với những bạn theo đuổi sự nhẹ nhàng từ tự nhiên, tìm về sự thư giản, cảm giác thoải mái."
              priceSi="LIÊN HỆ"
              priceLe="80.000 VNĐ/500g"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
            <ProductItem
              imgSrc="/products/sa/CayToS80_1.jpg"
              imgSrc1="/products/sa/CayToS80_1.jpg"
              imgSrc2="/products/sa/CayToS80_2.jpg"
              imgSrc3="/products/sa/CayToS80_1.jpg"
              imgSrc4="/products/sa/CayToS80_2.jpg"
              title="Hương Cây To | 80cm"
              price="4.000 VNĐ/cây"
              huonglieu="là sự kết hợp của các nguyên liệu từ tự nhiên như cây sả, keo bời lời cùng một số thảo dược khác. "
              muithom="hương sả có mùi thơm tươi mát, mạnh mẽ và kích thích. Tạo sự tỉnh táo và tăng sự tập trung.Xua đuổi muỗi mà không ảnh hướng đến sức khỏe còn người."
              kichthuoc="Có 80 cm, thời gian cháy gần 4 giờ. Tùy vào nhu cầu của bạn mà đặt kích cỡ thích hợp."
              theloai="Nhang cây to với kích thước 80cm, phù hợp để thắp các dịp lễ lớn, các đám ở tộc, hay đám cần thời canh nhang lâu."
              priceSi="LIÊN HỆ"
              priceLe="4.000 VNĐ/cây"
              chatLuongSP="Hương chúng tôi bán cũng là hương chúng tôi sử dụng. Dần dần chúng tôi sẽ làm kiểm định các loại nhang mà chúng tôi đã sản xuất để cả nhà yên tâm hơn."
              chinhSachDoiTra="TH1: Nếu trong quá trình vận chuyển, hương bị nứt mẻ thì hãy chụp và gửi lại chúng tôi, chúng tôi sẽ gửi lại cho bạn sản phẩm mới. TH2: Mọi sai xót mà cả nhà gặp phải khi sử dụng mà không hài lòng thì xin hãy nhắn ngay với chúng tôi, chúng tôi luôn sẵn sàng lắng nghe và cải thiện những sai xót của mình."
              ThoiGianGiaoHang="TH1: Nếu nhang có sẵn thì 3-4 ngày sẽ có hàng, và chúng ta trao đổi tiền ship. TH2: Nếu nhang không có sẵn thì 7 ngày sẽ có hàng. TH3: Nếu bạn sống gần đại lí của chúng tôi, thì thời gian giao sẽ nhanh và phí ship rẻ hơn."
            />
          </LayoutProductList>
        </LayoutProductPage>
      </LayoutContent>
    </>
  );
};

export default AllProducts;
